/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as CuratorSlugRouteImport } from './routes/curator.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorSlugRoute = CuratorSlugRouteImport.update({
  id: '/curator/$slug',
  path: '/curator/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/radio': typeof RadioRoute
  '/curator/$slug': typeof CuratorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/radio': typeof RadioRoute
  '/curator/$slug': typeof CuratorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/radio': typeof RadioRoute
  '/curator/$slug': typeof CuratorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/radio' | '/curator/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/radio' | '/curator/$slug'
  id: '__root__' | '/' | '/radio' | '/curator/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RadioRoute: typeof RadioRoute
  CuratorSlugRoute: typeof CuratorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator/$slug': {
      id: '/curator/$slug'
      path: '/curator/$slug'
      fullPath: '/curator/$slug'
      preLoaderRoute: typeof CuratorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RadioRoute: RadioRoute,
  CuratorSlugRoute: CuratorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
